import { createContext, useContext, useState, useLayoutEffect } from 'react';

const LanguageContext = createContext(null);

const translations = {
  en: {
    // Nav
    home: 'Home',
    auctions: 'Auctions',
    cart: 'Cart',
    orders: 'My Orders',
    profile: 'Profile',
    login: 'Log In',
    logout: 'Log Out',
    priceAlerts: 'Price Alerts',
    favorites: 'Favorites',
    settings: 'Settings',
    deleteAccount: 'Delete Account',
    myPriceRequests: 'My Price Requests',
    acceptedOffer: 'Accepted Offer',
    offerApprovedCheckoutToast: 'Your offer was accepted. You are now on checkout.',
    autoApproved: 'Auto-approved',
    // Home
    shopNow: 'Shop Now',
    liveAuctions: 'Live Auctions',
    heroAppStoreAria: 'Download on the App Store',
    heroGooglePlayAria: 'Get it on Google Play',
    heroGetApp: 'Get the app',
    livePrice: 'Live price drops happening now',
    heroTitle: 'The price drops over time\nSecure it before stock runs out.',
    heroDesc:
      'Shop a dynamic marketplace where every product\'s price falls in real time. Stock is limited and can run out.',
    allProducts: 'All Products',
    homeTabNewProducts: 'New Products',
    homeTabDeals: 'Deals',
    shopDealsSub: 'Featured deals at special prices',
    homeFeedTabsAria: 'Product feed',
    homeFeedEmptyNew: 'No products with live price drops right now.',
    homeFeedEmptyDeals: 'No featured deals right now. Super admin can flag products on the dashboard.',
    shopPromotion: 'Promotion',
    shopBestSellers: 'Best Sellers',
    shopBestSellersSub: 'Top picks shoppers love',
    shopNewArrivals: 'New Arrivals',
    shopNewArrivalsSub: 'Just added to the page',
    shopTrendingSub: 'Prices dropping live',
    shopAuctionRailTitle: 'Live Auctions',
    shopAuctionRailSub: 'Bid on exclusive items before time runs out',
    badgeBogoFree: '1+1 free',
    productAuctionBadge: 'Opportunity',
    shopNavHome: 'Home',
    shopNavDeals: 'Deals',
    shopNavCart: 'Your Cart',
    shopNavOrders: 'Your Orders',
    shopNavAccount: 'Your Account',
    shopBottomNavAria: 'Shop navigation',
    supplierAddMoreSave: 'Add more from this supplier',
    supplierGroupSubtotal: 'Subtotal',
    purchase: 'Purchase',
    decreaseQuantity: 'Decrease quantity',
    increaseQuantity: 'Increase quantity',
    removeFromCart: 'Remove from cart',
    sort: 'Sort',
    results: 'Results for',
    products: 'products',
    product: 'product',
    noProductsFound: 'No products found',
    tryDifferent: 'Try a different category or search term.',
    clearFilters: 'Clear Filters',
    category: 'Category',
    subcategory: 'Subcategory',
    stockType: 'Stock Type',
    all: 'All',
    byPieces: 'By Pieces',
    fullStock: 'Full Stock',
    priceDroppingSort: 'Price Dropping',
    priceLowHigh: 'Price: Low → High',
    priceHighLow: 'Price: High → Low',
    // Product
    selectStockOption: 'Select Stock Option',
    units: 'units',
    total: 'Total',
    includingVat: 'Including VAT',
    addToCart: 'Buy Now',
    added: 'Added!',
    priceAlert: 'Price Alert',
    setAlert: 'Set Alert',
    removeAlert: 'Remove',
    alertPlaceholder: 'Target price (SAR)',
    alertHint: 'Get notified when price drops to your target.',
    fastDelivery: 'Fast Delivery',
    securePayment: 'Secure Payment',
    qualityProducts: 'Quality Products',
    productDesc: 'Product Description',
    productExpiryDate: 'Expiry date',
    productProductionDate: 'Production date',
    floorPrice: 'Floor',
    current: 'Current',
    couldDrop: 'Price could drop',
    more: 'more',
    was: 'Was',
    stockOptionsUnavailable: 'Stock options unavailable for this product.',
    // Cart
    yourCart: 'Your Cart',
    cartEmpty: 'Your cart is empty',
    cartEmptyDesc: 'Add a product to get started.',
    browseProducts: 'Browse Products',
    clear: 'Clear',
    subtotal: 'Subtotal',
    deliveryFee: 'Delivery Fee',
    free: 'Free',
    proceedToCheckout: 'Proceed to Checkout',
    continueShopping: 'Continue Shopping',
    orderSummary: 'Order Summary',
    // Checkout
    address: 'Address',
    payment: 'Payment',
    done: 'Done',
    shippingAddress: 'Shipping Address',
    region: 'Region',
    city: 'City',
    district: 'District',
    street: 'Street',
    buildingNo: 'Building / Unit No.',
    nationalAddressCode: 'National Address Code',
    optional: 'optional',
    label: 'Label',
    deliveryNotes: 'Delivery Notes',
    continueToPayment: 'Continue to Payment',
    backToCart: 'Back to Cart',
    backToAddress: 'Back to Address',
    shippingTo: 'Shipping To',
    paymentPickupSectionTitle: 'Pickup at warehouse',
    paymentPickupSectionSubtitle:
      'No shipping address is required. Pay here, then collect your order from the supplier warehouse.',
    paymentPickupWarehouseCityLine: 'Warehouse city: {city}',
    edit: 'Edit',
    nationalAddress: 'National Address',
    paymentMethod: 'Payment Method',
    visaMada: 'Visa · Mastercard · Mada',
    tamaraSplit: 'Split into payments · 0% interest',
    bankTransferTitle: 'Bank Transfer',
    bankTransferDesc: 'Transfer to our bank account and upload your receipt',
    bankAccountDetails: 'Bank Account Details',
    bankName: 'Bank: Riyad Bank',
    bankIban: 'IBAN: SA1120000002236118159940',
    bankTransferUploadHint: 'After transferring, please upload an image or PDF of your transfer receipt.',
    bankTransferUploadLabel: 'Upload transfer receipt (image or PDF)',
    bankTransferUploadRequired: 'Please upload your transfer receipt before submitting.',
    bankTransferFailed: 'Bank transfer submission failed. Please try again.',
    submitBankTransfer: 'Submit Transfer',
    fileTooLarge: 'File must be under 10 MB.',
    tapRedirect: "You'll be redirected to Tap's secure payment page to enter your card details. Return here when done.",
    tamaraInfo: 'Buy now, pay in 4 installments',
    tamaraDesc: '0% interest · You\'ll be redirected to Tamara.',
    items: 'Items',
    payViaTap: 'Pay via Tap',
    continueToTamara: 'Continue to Tamara',
    orderPlaced: 'Order Placed!',
    orderPlacedDesc: "Your order has been placed successfully. You'll receive a confirmation soon.",
    viewOrders: 'View Orders',
    // Orders
    myOrders: 'My Orders',
    noOrdersYet: 'No orders yet',
    noOrdersDesc: 'Your orders will appear here once you make a purchase.',
    trackShipment: 'Track Shipment',
    orderDate: 'Order Date',
    // Login
    welcomeBack: 'Welcome back',
    phoneDesc: 'Enter your phone number to receive a one-time code.',
    phoneNumber: 'Phone Number',
    sendCode: 'Send Code',
    newToHasm: 'New to Hasm?',
    createAccount: 'Create account',
    // Register
    createYourAccount: 'Create your Account',
    nameLabel: 'Full Name',
    namePlaceholder: 'Your name',
    register: 'Create Account',
    haveAccount: 'Already have an account?',
    // OTP
    verifyPhone: 'Verify your phone',
    otpSentTo: 'We sent a 6-digit code to',
    verify: 'Verify',
    resend: 'Resend',
    // Profile
    accountSettings: 'Account Settings',
    appearance: 'Appearance',
    darkMode: 'Dark Mode',
    language: 'Language',
    english: 'English',
    arabic: 'Arabic',
    support: 'Support',
    termsOfService: 'Terms of Service',
    deleteAccountConfirm: 'Are you sure you want to delete your account? This cannot be undone.',
    // Alerts
    priceAlertsTitle: 'Price Alerts',
    noAlertsYet: 'No price alerts yet',
    noAlertsDesc: 'Set price alerts on products to get notified.',
    targetPrice: 'Target',
    currentPrice: 'Current',
    deleteAlert: 'Delete',
    // Auctions
    liveAuctionsTitle: 'Live Auctions',
    placeBid: 'Place Bid',
    currentBid: 'Current Bid',
    viewAndBid: 'View & bid',
    failedLoadAuction: 'Could not load this auction. Please try again.',
    auctionInitialPriceLabel: 'Initial price',
    auctionBidsCount: '{n} bids',
    auctionTimeLeftLabel: 'Time left',
    auctionYourBidLabel: 'Your bid',
    auctionRecentBidsHeading: 'Recent bids',
    auctionAnonymousBidder: 'Bidder {n}',
    auctionBidPlaceholder: 'Amount (SAR)',
    startingPrice: 'Starting Price',
    endsIn: 'Ends in',
    // Search
    search: 'Search products…',
    searchAction: 'Search',
    // Common
    loading: 'Loading…',
    retry: 'Retry',
    sar: 'SAR',
    selectRegion: 'Select region…',
    selectCity: 'Select city…',
    selectDistrict: 'Select district…',
    regionSearch: 'Search regions…',
    citySearch: 'Search cities…',
    districtSearch: 'Search neighborhoods…',
    noLocationMatches: 'No matching places',
    nationalAddressPlaceholder: '4 letters + 4 numbers',
    nationalAddressFormatHint: 'Must be 4 letters followed by 4 numbers',
    shippingAllFieldsRequired: 'All fields below are required.',
    completeShippingFields: 'Please fill in every shipping field, including region, city, district, street, building number, and national address (4 letters + 4 numbers).',
    streetPlaceholder: 'Street name',
    buildingPlaceholder: 'e.g. 12',
    deliveryNotesPlaceholder: 'Any delivery instructions…',
    addressHome: 'Home',
    office: 'Office',
    other: 'Other',
    quarter: 'Quarter',
    half: 'Half',
    full: 'Full',
    // Navbar / theme
    profileSettings: 'Profile & Settings',
    lightMode: 'Light Mode',
    ariaSearch: 'Search',
    ariaTheme: 'Toggle theme',
    ariaMenu: 'Menu',
    accountFallback: 'Account',
    // Cart toasts & labels
    loginToCheckout: 'Please log in to checkout',
    itemRemoved: 'Item removed',
    cartLineUnits: '{n} units',
    selectSize: 'Select size',
    selectSizeRequired: 'Please select a size',
    selectColor: 'Choose your color',
    selectColorRequired: 'Please select a color',
    sizeStockLeft: '{n} left',
    // Favorites
    favoritesTitle: 'Favorites',
    savedItemsCount: '{n} saved items',
    noFavoritesTitle: 'No favorites yet',
    noFavoritesDesc: 'Tap the heart icon on any product to save it here.',
    // Orders
    orderItemsFallback: 'Order items',
    orderMoreItems: '+{n} more',
    orderNumberShort: 'Order #{id}',
    itemsCountLabel: '{n} items',
    loginOrdersTitle: 'Log in to view your orders',
    loginOrdersDesc: 'You need to be logged in to see your order history.',
    startShopping: 'Start Shopping',
    moreItemsShort: '+{n} more',
    // Order status
    statusPending: 'Pending',
    statusConfirmed: 'Confirmed',
    statusProcessing: 'Processing',
    statusShipped: 'Shipped',
    statusDelivered: 'Delivered',
    statusCancelled: 'Cancelled',
    auctionEnded: 'Ended',
    checkoutCustomerDefault: 'Customer',
    profileDefaultDisplayName: 'User',
    // Auctions
    loginToBid: 'Log in to bid',
    bidMustHigher: 'Bid must be higher than {amount} SAR',
    bidPlaced: 'Bid of {amount} SAR placed!',
    bidFailed: 'Failed to place bid',
    youHaveWonAuctionMessage: 'You have won an auction. Please complete the purchase before bidding in another auction.',
    tabMyWins: 'My Wins',
    noLiveAuctions: 'No live auctions',
    noLiveAuctionsDesc: 'Check back soon for new auction events.',
    loginSeeWins: 'Log in to see your wins',
    noWinsTitle: 'No wins yet',
    noWinsDesc: 'Participate in live auctions to win exclusive items.',
    browseAuctionsBtn: 'Browse Auctions',
    goToCart: 'Go to Cart',
    wonBadge: 'WON',
    auctionOpportunityBadge: 'Opportunity',
    liveBadge: 'LIVE',
    liveBidding: 'Live Bidding',
    auctionsTitle: 'Auctions',
    auctionsIntro: 'Bid on exclusive items in real time. Highest bid when time runs out wins.',
    auctionItemFallback: 'Auction Item',
    wonItemFallback: 'Won Item',
    bidsLabel: 'Bids',
    bidMinPlaceholder: 'Min {amount} SAR',
    cancel: 'Cancel',
    close: 'Close',
    // Alerts page
    loginViewAlerts: 'Log in to view your alerts',
    alertsActiveCount: '{n} active alerts',
    alertsActiveCountOne: '1 active alert',
    alertsLongDesc: 'Set a target price on any product and we will notify you when it drops.',
    alertRemovedToast: 'Alert removed',
    alertRemoveFailed: 'Failed to remove alert',
    productFallback: 'Product',
    reachedTarget: 'Target reached!',
    yourTarget: 'Your Target',
    // Product page extras
    backToProducts: 'Back to products',
    bySupplier: 'by {name}',
    supplierMoreFromTitle: 'More from this supplier',
    supplierOtherProducts: 'Other products from this seller',
    percentOff: '-{n}% off',
    badgeDealSticker: '-{n}%',
    wasPriceLine: 'Was {amount} SAR',
    floorLine: 'Floor: {amount} SAR',
    priceDropMore: 'Price could drop {amount} SAR more',
    totalLine: 'Total:',
    totalPriceForPieces: 'Price for {quantity} pieces',
    msrpFullStockLead: 'Expected retail total for full stock is',
    removeAlertShort: 'Remove',
    setButton: 'Set',
    secureTapTitle: 'Secure card payment via Tap',
    tamaraInstallmentLine: '4 × {amount} SAR · 0% interest · You will be redirected to Tamara.',
    buyNow4Installments: 'Buy now, pay in 4 installments',
    // Checkout extras
    paymentMethodTitle: 'Payment Method',
    nationalAddressLine: 'National Address: {code}',
    qtyShort: 'Quantity: {n}',
    payViaTapAmount: 'Pay {amount} SAR via Tap',
    payViaTapLead: 'Pay',
    payViaTapTail: 'via Tap',
    tamaraInstallmentSuffix: '· 0% interest · You will be redirected to Tamara.',
    // Profile
    emailLabel: 'Email',
    deleteMyAccount: 'Delete my account',
    nameUpdated: 'Name updated',
    updateFailed: 'Failed to update',
    signedOut: 'Signed out',
    accountDeleted: 'Account deleted',
    deleteAccountFailed: 'Failed to delete account',
    // Login promo
    statPriceDrops: 'Price Drops',
    statSavingsDaily: 'Savings Daily',
    // OTP
    otpWelcome: 'Welcome back!',
    invalidOtp: 'Invalid code. Please try again.',
    codeResent: 'Code resent!',
    resendFailed: 'Failed to resend. Please try again.',
    // Auth errors
    failedSendOtp: 'Failed to send OTP. Please try again.',
    registrationFailed: 'Registration failed. Please try again.',
    // Footer
    footerTagline: 'Dynamic pricing marketplace where prices drop in real time. Shop smart, bid live, win big.',
    footerSocialLinkedIn: 'Hasm on LinkedIn',
    footerShop: 'Shop',
    footerAccount: 'Account',
    footerCategoryAll: 'All Products',
    footerCategoryFashion: 'Fashion',
    footerCategoryHomeLiving: 'Home & Living',
    footerCategoryElectronics: 'Electronics',
    footerSupplierTitle: 'Seller interest',
    footerSupplierLead:
      'Interested? Leave your phone number and we’ll get in touch.',
    footerSupplierPhoneAria: 'Phone number',
    footerSupplierPlaceholder: '+966 5X XXX XXXX',
    footerSupplierSend: 'Send',
    footerSupplierFormAria: 'Seller interest',
    footerSupplierEmailSubject: 'New Hasm seller interest',
    footerVatLogoAlt: 'VAT | ضريبة القيمة المضافة',
    footerVatRegistration: 'VAT Number: {vatNumber}',
    footerCrLogoAlt: 'Ministry of Commerce | وزارة التجارة',
    footerCommercialRegistration: 'CR Number: {crNumber}',
    footerRightsReserved: 'All rights reserved',
    footerEmpoweringTagline: 'Empowering dynamic pricing solutions',
    footerSecureReliable: 'Secure & Reliable',
    footerLightningFast: 'Lightning Fast',
    footerGetSupport: 'Get Support',
    footerContactUs: 'Contact Us',
    footerVisitWebsite: 'Visit our website',
    copyrightLine: '© {year} Hasm. All rights reserved.',
    /** Main / sub labels aligned with Mobile-production lib/l10n/app_*.arb (world_*, sub_*). */
    catFashion: 'Fashion',
    catHomeCat: 'Home',
    catHomeLiving: 'Home & Living',
    catKitchen: 'Kitchen',
    catLifestyle: 'Life Style',
    catConstruction: 'Construction',
    catElectronics: 'Electronics',
    brandName: 'Hasm',
    documentTitle: 'Hasm — Dynamic pricing marketplace',
    subOther: 'Other',
    subBedding: 'Bedding',
    subHomeEssentials: 'Home Essentials',
    subKitchenTools: 'Kitchen Tools',
    subCoffeeTools: 'Coffee tools',
    subRestaurantTools: 'Restaurant tools',
    subFoods: 'Foods',
    subHomeDecor: 'Home Decor',
    subMensClothing: "Men's Clothing",
    subWomensClothing: "Women's Clothing",
    subKidsClothing: "Kids' Clothing",
    subAccessories: 'Accessories',
    subBags: 'Bags',
    subShoes: 'Shoes',
    subBuildingMaterials: 'Building Materials',
    subPowerTools: 'Power Tools',
    subPlumbingTools: 'Plumbing Tools',
    subConstructionTools: 'Construction Tools',
    subTechAccessories: 'Tech Accessories',
    subOfficeSupplies: 'Office Supplies',
    subKidsToys: "Kids' Toys",
    smartphones: 'Smartphones',
    laptops: 'Laptops',
    tablets: 'Tablets',
    cameras: 'Cameras',
    gaming: 'Gaming',
    watches: 'Watches',
    fitness: 'Fitness',
    outdoor: 'Outdoor',
    teamSports: 'Team Sports',
    waterSports: 'Water Sports',
    cycling: 'Cycling',
    running: 'Running',
    skincare: 'Skincare',
    makeup: 'Makeup',
    fragrances: 'Fragrances',
    haircare: 'Haircare',
    nailCare: 'Nail Care',
    beautyTools: 'Beauty Tools',
    cookware: 'Cookware',
    appliances: 'Appliances',
    utensils: 'Utensils',
    storage: 'Storage',
    dining: 'Dining',
    bakeware: 'Bakeware',
    jewelry: 'Jewelry',
    sunglasses: 'Sunglasses',
    belts: 'Belts',
    wallets: 'Wallets',
    cardDroppingLabel: 'Dropping',
    viewProduct: 'View product',
    // Certified stamp
    certifiedTitle: 'Certified Products',
    certifiedSub: 'All products are verified and approved',
    certifiedBadge: 'Verified on Hasm',
    // Tamara ad
    tamaraAdHeadline: 'Shop now, pay later',
    tamaraAdSub: 'Split your purchase into interest-free installments',
    tamaraAdBadge: 'Available at checkout',
    // Hero stats
    heroStatRealtime: 'Real-time Prices',
    heroStatDropping: 'Products Dropping',
    heroStatSavings: 'Customer Savings',
    heroValueLive: 'Live',
    heroValueDropping: 'Non-stop',
    heroValueDaily: 'Daily',
    // Not found
    pageNotFoundTitle: 'Page not found',
    pageNotFoundDesc: 'The page you are looking for does not exist or has been moved.',
    backToHome: 'Back to Home',
    // Shipment tracking
    backToOrders: 'Back to Orders',
    trackShipmentTitle: 'Track Shipment',
    refresh: 'Refresh',
    trackingNumber: 'Tracking Number',
    carrier: 'Carrier',
    orderIdLabel: 'Order ID',
    statusLabel: 'Status',
    deliveryProgress: 'Delivery Progress',
    trackingHistory: 'Tracking History',
    currentStatus: 'Current status',
    stepOrderPlaced: 'Order Placed',
    stepOutForDelivery: 'Out for Delivery',
    statusUnknown: 'Unknown status',
    trackingEventGeneric: 'Shipment update',
    // ProductCard
    favAddedToast: 'Added to favorites',
    favRemovedToast: 'Removed from favorites',
    addToFavorites: 'Add to favorites',
    removeFromFavorites: 'Remove from favorites',
    productCardStock: 'Stock: {n}',
    productCardMsrpLabel: 'MSRP',
    badgeFreeDelivery: 'Free delivery',
    badgePickupOnly: 'Pickup only',
    badgePickupOnlyCity: 'Pickup only: {city}',
    pickupLocationTitle: 'Pickup location',
    viewPickupLocation: 'Warehouse & contact',
    warehouseAddressLabel: 'Address',
    contactPersonLabel: 'Contact',
    pickupInfoUnavailable:
      'Warehouse details are not available yet. Contact support if you need help.',
    pickupWarehousePendingBankTransfer: 'Warehouse appears after transfer confirmation.',
    currentPriceLabel: 'Current price',
    updateAlert: 'Update alert',
    setTargetPriceTitle: 'Set target price',
    updateTargetPriceTitle: 'Update target price',
    enterTargetPriceLabel: 'Target price',
    alertDescription:
      'The alert will be triggered when the price drops to or below this amount',
    targetPriceMustBeLower: 'Target price must be lower than the current price',
    pleaseEnterValidPrice: 'Please enter a valid price',
    // Product errors
    productNotFound: 'Product not found',
    selectStockToast: 'Please select a stock option',
    addedToCartToast: 'Added to cart!',
    loginPriceAlerts: 'Log in to set price alerts',
    alertSetToast: 'Alert set for {amount} SAR',
    alertSetFailed: 'Failed to set alert',
    alertRemovedToast2: 'Alert removed',
    alertRemoveFailedToast: 'Failed to remove alert',
    loginAlertsShort: 'Log in to set alerts',
    requestPriceFromSeller: 'Submit a price to the seller',
    requestOfferCta: 'Submit a price to the seller',
    sendRequest: 'Send Request',
    offeredPrice: 'Offered Price',
    expectedProfitDiff: 'Expected resale profit',
    quantity: 'Quantity',
    messageOptional: 'Message (optional)',
    loginPriceRequest: 'Log in to request a price',
    invalidPriceRequestValues: 'Enter a valid quantity and offered price',
    priceRequestSent: 'Price request sent',
    priceRequestFailed: 'Failed to send price request',
    priceRequestUnavailable: 'Seller info is unavailable for this product',
    noPriceRequestsYet: 'No price requests yet',
    sampleRequestCta: 'Request sample',
    sampleRequestDialogTitle: 'Request a product sample',
    sampleRequestDialogBody: 'We will notify the team. You can add an optional note below.',
    sampleRequestSent: 'Sample request sent',
    sampleRequestFailed: 'Could not send sample request',
    loginSampleRequest: 'Log in to request a sample',
    // Checkout toasts
    completeTapTab: 'Complete your payment in the Tap tab, then return here.',
    productNotShippable:
      '«{name}» cannot be shipped — unit dimensions or weight exceed carrier limits (max 50×50×50 cm, max 15 kg per shipment). Edit the product dimensions/weight in the dashboard, or mark it warehouse pickup / full stock if that applies.',
    paymentFailedGeneric: 'Payment failed. Please try again.',
    paymentNotCompleted: 'Payment was not completed. Please try again.',
    paymentTimeout: 'Payment timed out. Check your orders for confirmation.',
    confirmPaymentFailed: 'Could not confirm payment. Check your orders.',
    completeTamaraTab: 'Complete your Tamara payment in the new tab, then return here.',
    tamaraFailed: 'Tamara payment failed. Please try again.',
    paymentCardTitle: 'Credit / Debit Card',
    paymentTamaraTitle: 'Tamara — Buy Now, Pay Later',
    itemsInOrder: 'Items ({n})',
    loginHeroTitle1: 'Prices that drop',
    loginHeroTitle2: 'while you watch.',
    loginHeroBody: 'Shop on a dynamic marketplace where every product\'s price falls in real time. Bid on exclusive auctions. Set price alerts. Win big.',
    loginStatProductsValue: 'Dynamic',
    loginStatProducts: 'Products',
    loginStatLive: 'Live',
    registerHeroTitle1: 'Watch prices drop',
    registerHeroTitle2: 'and save when you shop.',
    registerHeroBody: 'Create your account to track live price drops, set alerts, and bid on exclusive auctions — all in one place.',
    registerIntro: 'Enter your name and phone number to get started.',
    otpEnterCode: 'Enter your code',
    otpSentLine: 'We sent a {n}-digit code to',
    verifyCode: 'Verify Code',
    changeNumber: 'Change number',
    resendIn: 'Resend in {s}s',
    resendCode: 'Resend Code',
    deleteAccountTitle: 'Delete Account?',
    phoneExamplePlaceholder: '5X XXX XXXX',
    profileGuestTitle: 'Log in to view your profile',
    profileGuestDesc: 'Access your orders, favorites, and settings.',
    dangerZone: 'Danger Zone',
    loginCopyright: '© {year} Hasm Platform',
  },
  ar: {
    // Nav
    home: 'الرئيسية',
    auctions: 'المزادات',
    cart: 'السلة',
    orders: 'طلباتي',
    profile: 'الملف الشخصي',
    login: 'تسجيل الدخول',
    logout: 'تسجيل الخروج',
    priceAlerts: 'تنبيهات السعر',
    favorites: 'المفضلة',
    settings: 'الإعدادات',
    deleteAccount: 'حذف الحساب',
    myPriceRequests: 'طلبات السعر الخاصة بي',
    acceptedOffer: 'عرض مقبول',
    offerApprovedCheckoutToast: 'تم قبول عرضك. تم الانتقال للدفع.',
    autoApproved: 'تمت الموافقة تلقائيًا',
    // Home
    shopNow: 'تسوق الآن',
    liveAuctions: 'المزادات المباشرة',
    heroAppStoreAria: 'تنزيل من App Store',
    heroGooglePlayAria: 'احصل عليه من Google Play',
    heroGetApp: 'حمّل التطبيق',
    livePrice: 'انخفاض أسعار مباشرة الآن',
    heroTitle: 'السعر ينخفض مع الوقت\nاحجزه قبل نفاد المخزون',
    heroDesc:
      'تسوق في سوق ديناميكي حيث ينخفض سعر كل منتج بشكل مباشر. المخزون محدود وقد ينفد في أي لحظة.',
    allProducts: 'جميع المنتجات',
    homeTabNewProducts: 'منتجات جديدة',
    homeTabDeals: 'صفقات',
    shopDealsSub: 'صفقات مميزة بأسعار خاصة',
    homeFeedTabsAria: 'تصفح المنتجات',
    homeFeedEmptyNew: 'لا توجد منتجات بانخفاض سعر مباشر حالياً.',
    homeFeedEmptyDeals: 'لا توجد صفقات مميزة حالياً. يمكن للمشرف العام تفعيلها من لوحة التحكم.',
    shopPromotion: 'الترويج',
    shopBestSellers: 'الأكثر مبيعاً',
    shopBestSellersSub: 'الأكثر طلباً من عملائنا',
    shopNewArrivals: 'وصل حديثاً',
    shopNewArrivalsSub: 'أضيفت للتو للصفحه',
    shopTrendingSub: 'الأسعار تنزل مباشرة',
    shopAuctionRailTitle: 'المزادات المباشرة',
    shopAuctionRailSub: 'زايد على منتجات حصرية قبل انتهاء الوقت',
    badgeBogoFree: '1+1 مجاناً',
    productAuctionBadge: 'فرصه',
    shopNavHome: 'الرئيسية',
    shopNavDeals: 'الصفقات',
    shopNavCart: 'سلتك',
    shopNavOrders: 'طلباتك',
    shopNavAccount: 'حسابك',
    shopBottomNavAria: 'تنقل المتجر',
    supplierAddMoreSave: 'أضف المزيد من هذا المورد',
    supplierGroupSubtotal: 'المجموع الفرعي',
    purchase: 'شراء',
    decreaseQuantity: 'تقليل الكمية',
    increaseQuantity: 'زيادة الكمية',
    removeFromCart: 'إزالة من السلة',
    sort: 'ترتيب',
    results: 'نتائج البحث عن',
    products: 'منتجات',
    product: 'منتج',
    noProductsFound: 'لم يتم العثور على منتجات',
    tryDifferent: 'جرب فئة مختلفة أو مصطلح بحث آخر.',
    clearFilters: 'مسح الفلاتر',
    category: 'الفئة',
    subcategory: 'التصنيف الفرعي',
    stockType: 'نوع المخزون',
    all: 'الكل',
    byPieces: 'بالقطعة',
    fullStock: 'مخزون كامل',
    priceDroppingSort: 'السعر الأسرع انخفاضاً',
    priceLowHigh: 'السعر: من الأقل',
    priceHighLow: 'السعر: من الأعلى',
    // Product
    selectStockOption: 'اختر خيار المخزون',
    units: 'وحدة',
    total: 'الإجمالي',
    includingVat: 'شامل ضريبة القيمة المضافة',
    addToCart: 'اطلب الآن',
    added: 'تمت الإضافة!',
    priceAlert: 'تنبيه السعر',
    setAlert: 'تعيين تنبيه',
    removeAlert: 'إزالة',
    alertPlaceholder: 'السعر المستهدف (ر.س)',
    alertHint: 'سيتم إشعارك عند وصول السعر لهدفك.',
    fastDelivery: 'توصيل سريع',
    securePayment: 'دفع آمن',
    qualityProducts: 'منتجات عالية الجودة',
    productDesc: 'وصف المنتج',
    productExpiryDate: 'تاريخ الانتهاء',
    productProductionDate: 'تاريخ الإنتاج',
    floorPrice: 'السعر الأدنى',
    current: 'الحالي',
    couldDrop: 'قد ينخفض السعر',
    more: 'إضافية',
    was: 'كان',
    stockOptionsUnavailable: 'خيارات المخزون غير متاحة لهذا المنتج.',
    // Cart
    yourCart: 'سلتك',
    cartEmpty: 'سلتك فارغة',
    cartEmptyDesc: 'أضف منتجاً للبدء.',
    browseProducts: 'تصفح المنتجات',
    clear: 'مسح',
    subtotal: 'المجموع الفرعي',
    deliveryFee: 'رسوم التوصيل',
    free: 'مجاناً',
    proceedToCheckout: 'إتمام الطلب',
    continueShopping: 'مواصلة التسوق',
    orderSummary: 'ملخص الطلب',
    // Checkout
    address: 'العنوان',
    payment: 'الدفع',
    done: 'تم',
    shippingAddress: 'عنوان الشحن',
    region: 'المنطقة',
    city: 'المدينة',
    district: 'الحي',
    street: 'الشارع',
    buildingNo: 'رقم المبنى / الوحدة',
    nationalAddressCode: 'رمز العنوان الوطني',
    optional: 'اختياري',
    label: 'التسمية',
    deliveryNotes: 'ملاحظات التوصيل',
    continueToPayment: 'المتابعة للدفع',
    backToCart: 'العودة للسلة',
    backToAddress: 'العودة للعنوان',
    shippingTo: 'الشحن إلى',
    paymentPickupSectionTitle: 'الاستلام من المستودع',
    paymentPickupSectionSubtitle:
      'لا حاجة لعنوان توصيل. أكمل الدفع هنا، ثم استلم طلبك من مستودع المورد.',
    paymentPickupWarehouseCityLine: 'مدينة المستودع: {city}',
    edit: 'تعديل',
    nationalAddress: 'العنوان الوطني',
    paymentMethod: 'طريقة الدفع',
    visaMada: 'فيزا · ماستركارد · مدى',
    tamaraSplit: 'قسّم إلى دفعات · 0% فائدة',
    bankTransferTitle: 'تحويل بنكي',
    bankTransferDesc: 'تحويل إلى حسابنا البنكي ورفع إثبات التحويل',
    bankAccountDetails: 'بيانات الحساب البنكي',
    bankName: 'البنك: الرياض',
    bankIban: 'رقم الآيبان: SA1120000002236118159940',
    bankTransferUploadHint: 'بعد التحويل، يرجى رفع صورة أو ملف PDF لإيصال التحويل.',
    bankTransferUploadLabel: 'رفع إيصال التحويل (صورة أو PDF)',
    bankTransferUploadRequired: 'يرجى رفع إيصال التحويل قبل الإرسال.',
    bankTransferFailed: 'فشل إرسال طلب التحويل. يرجى المحاولة مجدداً.',
    submitBankTransfer: 'إرسال التحويل',
    fileTooLarge: 'يجب أن يكون حجم الملف أقل من 10 ميجابايت.',
    tapRedirect: 'سيتم توجيهك إلى صفحة الدفع الآمنة من Tap لإدخال بيانات بطاقتك. عد هنا عند الانتهاء.',
    tamaraInfo: 'اشترِ الآن وادفع على 4 أقساط',
    tamaraDesc: '0% فائدة · سيتم توجيهك إلى تمارا.',
    items: 'المنتجات',
    payViaTap: 'الدفع عبر Tap',
    continueToTamara: 'المتابعة إلى تمارا',
    orderPlaced: 'تم تقديم الطلب!',
    orderPlacedDesc: 'تم تقديم طلبك بنجاح. ستتلقى تأكيداً قريباً.',
    viewOrders: 'عرض الطلبات',
    // Orders
    myOrders: 'طلباتي',
    noOrdersYet: 'لا توجد طلبات بعد',
    noOrdersDesc: 'ستظهر طلباتك هنا بعد إجراء عملية شراء.',
    trackShipment: 'تتبع الشحنة',
    orderDate: 'تاريخ الطلب',
    // Login
    welcomeBack: 'مرحباً بعودتك',
    phoneDesc: 'أدخل رقم هاتفك لاستقبال رمز التحقق.',
    phoneNumber: 'رقم الجوال',
    sendCode: 'إرسال الرمز',
    newToHasm: 'جديد في حسم؟',
    createAccount: 'إنشاء حساب',
    // Register
    createYourAccount: 'إنشاء حسابك',
    nameLabel: 'الاسم الكامل',
    namePlaceholder: 'اسمك',
    register: 'إنشاء الحساب',
    haveAccount: 'لديك حساب بالفعل؟',
    // OTP
    verifyPhone: 'تحقق من هاتفك',
    otpSentTo: 'أرسلنا رمزاً مكوناً من 6 أرقام إلى',
    verify: 'تحقق',
    resend: 'إعادة الإرسال',
    // Profile
    accountSettings: 'إعدادات الحساب',
    appearance: 'المظهر',
    darkMode: 'الوضع الداكن',
    language: 'اللغة',
    english: 'الإنجليزية',
    arabic: 'العربية',
    support: 'الدعم',
    termsOfService: 'الشروط والأحكام',
    deleteAccountConfirm: 'هل أنت متأكد من رغبتك في حذف حسابك؟ لا يمكن التراجع عن هذا الإجراء.',
    // Alerts
    priceAlertsTitle: 'تنبيهات السعر',
    noAlertsYet: 'لا توجد تنبيهات سعر بعد',
    noAlertsDesc: 'عيّن تنبيهات السعر على المنتجات ليتم إشعارك.',
    targetPrice: 'المستهدف',
    currentPrice: 'الحالي',
    deleteAlert: 'حذف',
    // Auctions
    liveAuctionsTitle: 'المزادات المباشرة',
    placeBid: 'المزايدة',
    currentBid: 'المزايدة الحالية',
    viewAndBid: 'عرض والمزايدة',
    failedLoadAuction: 'تعذر تحميل المزاد. حاول مرة أخرى.',
    auctionInitialPriceLabel: 'السعر الابتدائي',
    auctionBidsCount: '{n} مزايدة',
    auctionTimeLeftLabel: 'الوقت المتبقي',
    auctionYourBidLabel: 'مزايدتك',
    auctionRecentBidsHeading: 'آخر المزايدات',
    auctionAnonymousBidder: 'مزايد {n}',
    auctionBidPlaceholder: 'المبلغ (ر.س)',
    startingPrice: 'سعر البداية',
    endsIn: 'ينتهي في',
    // Search
    search: 'ابحث عن منتجات…',
    searchAction: 'بحث',
    // Common
    loading: 'جاري التحميل…',
    retry: 'إعادة المحاولة',
    sar: 'ر.س',
    selectRegion: 'اختر المنطقة…',
    selectCity: 'اختر المدينة…',
    selectDistrict: 'اختر الحي…',
    regionSearch: 'بحث في المناطق…',
    citySearch: 'بحث في المدن…',
    districtSearch: 'بحث في الأحياء…',
    noLocationMatches: 'لا توجد نتائج مطابقة',
    nationalAddressPlaceholder: '4 أحرف + 4 أرقام',
    nationalAddressFormatHint: 'يجب أن يكون 4 أحرف ثم 4 أرقام',
    shippingAllFieldsRequired: 'جميع الحقول أدناه إلزامية.',
    completeShippingFields: 'يرجى تعبئة جميع حقول عنوان الشحن: المنطقة، المدينة، الحي، الشارع، رقم المبنى، ورمز العنوان الوطني (4 أحرف + 4 أرقام).',
    streetPlaceholder: 'اسم الشارع',
    buildingPlaceholder: 'مثال: 12',
    deliveryNotesPlaceholder: 'تعليمات التوصيل…',
    addressHome: 'المنزل',
    office: 'العمل',
    other: 'أخرى',
    quarter: 'ربع',
    half: 'نصف',
    full: 'كامل',
    // Navbar / theme
    profileSettings: 'الملف والإعدادات',
    lightMode: 'الوضع الفاتح',
    ariaSearch: 'بحث',
    ariaTheme: 'تبديل المظهر',
    ariaMenu: 'القائمة',
    accountFallback: 'الحساب',
    // Cart
    loginToCheckout: 'يرجى تسجيل الدخول لإتمام الطلب',
    itemRemoved: 'تمت إزالة المنتج',
    cartLineUnits: '{n} وحدة',
    selectSize: 'اختر المقاس',
    selectSizeRequired: 'يرجى اختيار المقاس',
    selectColor: 'اختر اللون',
    selectColorRequired: 'يرجى اختيار اللون',
    sizeStockLeft: 'متبقي {n}',
    // Favorites
    favoritesTitle: 'المفضلة',
    savedItemsCount: '{n} عناصر محفوظة',
    noFavoritesTitle: 'لا توجد مفضلات بعد',
    noFavoritesDesc: 'اضغط على أيقونة القلب على أي منتج لحفظه هنا.',
    // Orders
    orderItemsFallback: 'عناصر الطلب',
    orderMoreItems: '+{n} إضافية',
    orderNumberShort: 'طلب #{id}',
    itemsCountLabel: '{n} عناصر',
    loginOrdersTitle: 'سجّل الدخول لعرض طلباتك',
    loginOrdersDesc: 'تحتاج لتسجيل الدخول لعرض سجل طلباتك.',
    startShopping: 'ابدأ التسوق',
    moreItemsShort: '+{n} أخرى',
    // Order status
    statusPending: 'قيد الانتظار',
    statusConfirmed: 'مؤكد',
    statusProcessing: 'قيد التجهيز',
    statusShipped: 'تم الشحن',
    statusDelivered: 'تم التسليم',
    statusCancelled: 'ملغى',
    auctionEnded: 'انتهى',
    checkoutCustomerDefault: 'عميل',
    profileDefaultDisplayName: 'مستخدم',
    // Auctions
    loginToBid: 'سجّل الدخول للمزايدة',
    bidMustHigher: 'يجب أن تكون المزايدة أعلى من {amount} ر.س',
    bidPlaced: 'تم تقديم مزايدة {amount} ر.س!',
    bidFailed: 'فشل تقديم المزايدة',
    youHaveWonAuctionMessage: 'لقد فزت في مزاد. يرجى إتمام الشراء قبل المزايدة في مزاد آخر.',
    tabMyWins: 'مكاسبي',
    noLiveAuctions: 'لا توجد مزادات مباشرة',
    noLiveAuctionsDesc: 'عد لاحقاً لمزادات جديدة.',
    loginSeeWins: 'سجّل الدخول لعرض مكاسبك',
    noWinsTitle: 'لا مكاسب بعد',
    noWinsDesc: 'شارك في المزادات المباشرة للفوز بعناصر حصرية.',
    browseAuctionsBtn: 'تصفح المزادات',
    goToCart: 'الذهاب للسلة',
    wonBadge: 'فزت',
    auctionOpportunityBadge: 'فرصة',
    liveBadge: 'مباشر',
    liveBidding: 'مزايدة مباشرة',
    auctionsTitle: 'المزادات',
    auctionsIntro: 'زايد على منتجات حصرية بشكل مباشر. أعلى مزايدة عند انتهاء الوقت يفوز.',
    auctionItemFallback: 'عنصر مزاد',
    wonItemFallback: 'عنصر مكتسب',
    bidsLabel: 'مزايدات',
    bidMinPlaceholder: 'الحد الأدنى {amount} ر.س',
    cancel: 'إلغاء',
    close: 'إغلاق',
    // Alerts
    loginViewAlerts: 'سجّل الدخول لعرض تنبيهاتك',
    alertsActiveCount: '{n} تنبيهات نشطة',
    alertsActiveCountOne: 'تنبيه نشط واحد',
    alertsLongDesc: 'عيّن سعراً مستهدفاً لأي منتج وسنُشعرك عند انخفاض السعر.',
    alertRemovedToast: 'تم حذف التنبيه',
    alertRemoveFailed: 'تعذر حذف التنبيه',
    productFallback: 'منتج',
    reachedTarget: 'تم الوصول للهدف!',
    yourTarget: 'هدفك',
    // Product page
    backToProducts: 'العودة للمنتجات',
    bySupplier: 'من {name}',
    supplierMoreFromTitle: 'المزيد من هذا المورد',
    supplierOtherProducts: 'منتجات أخرى من نفس البائع',
    percentOff: '-{n}٪ خصم',
    badgeDealSticker: 'خصم {n}٪',
    wasPriceLine: 'كان {amount} ر.س',
    floorLine: 'الأدنى: {amount} ر.س',
    priceDropMore: 'قد ينخفض السعر {amount} ر.س إضافية',
    totalLine: 'الإجمالي:',
    totalPriceForPieces: 'السعر لـ {quantity} قطعة',
    msrpFullStockLead: 'سعر البيع المتوقع لكامل الكمية هو',
    removeAlertShort: 'إزالة',
    setButton: 'تعيين',
    secureTapTitle: 'دفع آمن بالبطاقة عبر Tap',
    tamaraInstallmentLine: '4 × {amount} ر.س · 0% فائدة · سيتم توجيهك إلى تمارا.',
    buyNow4Installments: 'اشترِ الآن وادفع على 4 أقساط',
    // Checkout
    paymentMethodTitle: 'طريقة الدفع',
    nationalAddressLine: 'العنوان الوطني: {code}',
    qtyShort: 'الكمية: {n}',
    payViaTapAmount: 'ادفع {amount} ر.س عبر Tap',
    payViaTapLead: 'ادفع',
    payViaTapTail: 'عبر Tap',
    tamaraInstallmentSuffix: '· 0% فائدة · سيتم توجيهك إلى تمارا.',
    // Profile
    emailLabel: 'البريد الإلكتروني',
    deleteMyAccount: 'حذف حسابي',
    nameUpdated: 'تم تحديث الاسم',
    updateFailed: 'فشل التحديث',
    signedOut: 'تم تسجيل الخروج',
    accountDeleted: 'تم حذف الحساب',
    deleteAccountFailed: 'فشل حذف الحساب',
    // Login
    statPriceDrops: 'انخفاض السعر',
    statSavingsDaily: 'توفير يومي',
    // OTP
    otpWelcome: 'مرحباً بعودتك!',
    invalidOtp: 'رمز غير صحيح. حاول مرة أخرى.',
    codeResent: 'تم إعادة إرسال الرمز!',
    resendFailed: 'فشل إعادة الإرسال. حاول مرة أخرى.',
    // Auth
    failedSendOtp: 'فشل إرسال الرمز. حاول مرة أخرى.',
    registrationFailed: 'فشل التسجيل. حاول مرة أخرى.',
    // Footer
    footerTagline: 'سوق تسعير ديناميكي حيث تنخفض الأسعار بشكل مباشر. تسوق بذكاء، زايد مباشرة، واربح.',
    footerSocialLinkedIn: 'حسم على لينكد إن',
    footerShop: 'تسوق',
    footerAccount: 'الحساب',
    footerCategoryAll: 'جميع المنتجات',
    footerCategoryFashion: 'الموضة',
    footerCategoryHomeLiving: 'المنزل والمعيشة',
    footerCategoryElectronics: 'إلكترونيات',
    footerSupplierTitle: 'اهتمام البائعين',
    footerSupplierLead: 'مهتم؟ اترك رقم هاتفك وسنتواصل معك.',
    footerSupplierPhoneAria: 'رقم الهاتف',
    footerSupplierPlaceholder: '+966 5X XXX XXXX',
    footerSupplierSend: 'إرسال',
    footerSupplierFormAria: 'نموذج اهتمام البائعين',
    footerSupplierEmailSubject: 'طلب اهتمام بائع جديد — حسم',
    footerVatLogoAlt: 'ضريبة القيمة المضافة',
    footerVatRegistration: 'الرقم الضريبي: {vatNumber}',
    footerCrLogoAlt: 'وزارة التجارة',
    footerCommercialRegistration: 'رقم السجل: {crNumber}',
    footerRightsReserved: 'جميع الحقوق محفوظة',
    footerEmpoweringTagline: 'تمكين حلول التسعير الديناميكية',
    footerSecureReliable: 'آمن وموثوق',
    footerLightningFast: 'سريع جداً',
    footerGetSupport: 'الحصول على الدعم',
    footerContactUs: 'اتصل بنا',
    footerVisitWebsite: 'زر موقعنا الإلكتروني',
    copyrightLine: '© {year} حسم. جميع الحقوق محفوظة.',
    // Home categories (match mobile app .arb)
    catFashion: 'الموضة',
    catHomeCat: 'المنزل',
    catHomeLiving: 'المنزل والمعيشة',
    catKitchen: 'المطبخ',
    catLifestyle: 'أسلوب الحياة',
    catConstruction: 'البناء',
    catElectronics: 'إلكترونيات',
    brandName: 'حسم',
    documentTitle: 'حسم — سوق التسعير الديناميكي',
    subOther: 'أخرى',
    subBedding: 'مفارش',
    subHomeEssentials: 'لوازم منزلية',
    subKitchenTools: 'أدوات مطبخ',
    subCoffeeTools: 'أدوات القهوة',
    subRestaurantTools: 'أدوات المطعم',
    subFoods: 'أغذية',
    subHomeDecor: 'ديكور منزلي',
    subMensClothing: 'ملابس رجالية',
    subWomensClothing: 'ملابس نسائية',
    subKidsClothing: 'ملابس أطفال',
    subAccessories: 'إكسسوارات',
    subBags: 'شنط',
    subShoes: 'أحذية',
    subBuildingMaterials: 'مواد بناء',
    subPowerTools: 'أدوات كهربائية',
    subPlumbingTools: 'أدوات سباكة',
    subConstructionTools: 'عدد بناء',
    subTechAccessories: 'إكسسوارات تقنية',
    subOfficeSupplies: 'أدوات مكتبية',
    subKidsToys: 'ألعاب أطفال',
    smartphones: 'هواتف ذكية',
    laptops: 'أجهزة كمبيوتر محمولة',
    tablets: 'أجهزة لوحية',
    cameras: 'كاميرات',
    gaming: 'ألعاب',
    watches: 'ساعات',
    fitness: 'لياقة بدنية',
    outdoor: 'أنشطة خارجية',
    teamSports: 'رياضات جماعية',
    waterSports: 'رياضات مائية',
    cycling: 'دراجات',
    running: 'جري',
    skincare: 'العناية بالبشرة',
    makeup: 'مكياج',
    fragrances: 'عطور',
    haircare: 'العناية بالشعر',
    nailCare: 'العناية بالأظافر',
    beautyTools: 'أدوات التجميل',
    cookware: 'أدوات الطبخ',
    appliances: 'أجهزة',
    utensils: 'أدوات المائدة',
    storage: 'تخزين',
    dining: 'طعام',
    bakeware: 'أدوات الخبز',
    jewelry: 'مجوهرات',
    sunglasses: 'نظارات شمسية',
    belts: 'أحزمة',
    wallets: 'محافظ',
    cardDroppingLabel: 'ينخفض',
    viewProduct: 'عرض المنتج',
    // Certified stamp
    certifiedTitle: 'منتجات معتمدة',
    certifiedSub: 'جميع المنتجات موثّقة ومعتمدة',
    certifiedBadge: 'معتمد من حسم',
    // Tamara ad
    tamaraAdHeadline: 'اشترِ الآن وادفع لاحقاً',
    tamaraAdSub: 'قسّم مشترياتك على أقساط بدون فوائد',
    tamaraAdBadge: 'متاح عند الدفع',
    // Hero stats
    heroStatRealtime: 'أسعار لحظية',
    heroStatDropping: 'منتجات تنخفض أسعارها',
    heroStatSavings: 'توفير للعملاء',
    heroValueLive: 'مباشر',
    heroValueDropping: 'مستمر',
    heroValueDaily: 'يومياً',
    // Not found
    pageNotFoundTitle: 'الصفحة غير موجودة',
    pageNotFoundDesc: 'الصفحة التي تبحث عنها غير موجودة أو تم نقلها.',
    backToHome: 'العودة للرئيسية',
    // Shipment
    backToOrders: 'العودة للطلبات',
    trackShipmentTitle: 'تتبع الشحنة',
    refresh: 'تحديث',
    trackingNumber: 'رقم التتبع',
    carrier: 'الناقل',
    orderIdLabel: 'رقم الطلب',
    statusLabel: 'الحالة',
    deliveryProgress: 'تقدم التوصيل',
    trackingHistory: 'سجل التتبع',
    currentStatus: 'الحالة الحالية',
    stepOrderPlaced: 'تم الطلب',
    stepOutForDelivery: 'خارج للتوصيل',
    statusUnknown: 'حالة غير معروفة',
    trackingEventGeneric: 'تحديث الشحنة',
    // ProductCard
    favAddedToast: 'أُضيفت للمفضلة',
    favRemovedToast: 'أُزيلت من المفضلة',
    addToFavorites: 'إضافة إلى المفضلة',
    removeFromFavorites: 'إزالة من المفضلة',
    productCardStock: 'المخزون: {n}',
    productCardMsrpLabel: 'سعر التجزئة المقترح',
    badgeFreeDelivery: 'توصيل مجاني',
    badgePickupOnly: 'استلام فقط',
    badgePickupOnlyCity: 'استلام فقط: {city}',
    pickupLocationTitle: 'موقع الاستلام',
    viewPickupLocation: 'المستودع والتواصل',
    warehouseAddressLabel: 'العنوان',
    contactPersonLabel: 'جهة الاتصال',
    pickupInfoUnavailable:
      'تفاصيل المستودع غير متوفرة بعد. تواصل مع الدعم إذا احتجت مساعدة.',
    pickupWarehousePendingBankTransfer: 'يظهر المستودع بعد تأكيد التحويل.',
    currentPriceLabel: 'السعر الحالي',
    updateAlert: 'تحديث التنبيه',
    setTargetPriceTitle: 'تعيين السعر المستهدف',
    updateTargetPriceTitle: 'تحديث السعر المستهدف',
    enterTargetPriceLabel: 'السعر المستهدف',
    alertDescription:
      'سيتم تنبيهك عندما ينخفض السعر إلى هذا المبلغ أو أقل',
    targetPriceMustBeLower: 'يجب أن يكون السعر المستهدف أقل من السعر الحالي',
    pleaseEnterValidPrice: 'يرجى إدخال سعر صحيح',
    // Product
    productNotFound: 'المنتج غير موجود',
    selectStockToast: 'يرجى اختيار خيار المخزون',
    addedToCartToast: 'أُضيفت للسلة!',
    loginPriceAlerts: 'سجّل الدخول لتعيين تنبيهات السعر',
    alertSetToast: 'تم تعيين التنبيه عند {amount} ر.س',
    alertSetFailed: 'فشل تعيين التنبيه',
    alertRemovedToast2: 'تم حذف التنبيه',
    alertRemoveFailedToast: 'فشل حذف التنبيه',
    loginAlertsShort: 'سجّل الدخول لتعيين التنبيه',
    requestPriceFromSeller: 'تقديم سعر للبائع',
    requestOfferCta: 'تقديم سعر للبائع',
    sendRequest: 'إرسال الطلب',
    offeredPrice: 'السعر المقترح',
    expectedProfitDiff: 'توقع ربح إعادة البيع',
    quantity: 'الكمية',
    messageOptional: 'رسالة (اختياري)',
    loginPriceRequest: 'سجّل الدخول لطلب السعر',
    invalidPriceRequestValues: 'أدخل كمية وسعراً مقترحاً صحيحين',
    priceRequestSent: 'تم إرسال طلب السعر',
    priceRequestFailed: 'فشل إرسال طلب السعر',
    priceRequestUnavailable: 'بيانات البائع غير متاحة لهذا المنتج',
    noPriceRequestsYet: 'لا توجد طلبات سعر بعد',
    sampleRequestCta: 'طلب عينة',
    sampleRequestDialogTitle: 'طلب عينة من المنتج',
    sampleRequestDialogBody: 'سنُبلّغ الفريق. يمكنك إضافة ملاحظة اختيارية أدناه.',
    sampleRequestSent: 'تم إرسال طلب العينة',
    sampleRequestFailed: 'تعذر إرسال طلب العينة',
    loginSampleRequest: 'سجّل الدخول لطلب عينة',
    // Checkout toasts
    completeTapTab: 'أكمل الدفع في تبويب Tap ثم عد هنا.',
    productNotShippable:
      'لا يمكن شحن «{name}» — أبعاد أو وزن المنتج يتجاوز حدود الشحن (حد أقصى 50×50×50 سم للوحدة، و15 كغ للشحنة). عدّل الطول/العرض/الارتفاع/الوزن من لوحة التحكم، أو فعّل «استلام من المستودع» أو «بيع الكمية كاملة» إن كان ذلك مناسباً.',
    paymentFailedGeneric: 'فشل الدفع. حاول مرة أخرى.',
    paymentNotCompleted: 'لم يكتمل الدفع. حاول مرة أخرى.',
    paymentTimeout: 'انتهت مهلة الدفع. راجع طلباتك للتأكيد.',
    confirmPaymentFailed: 'تعذر تأكيد الدفع. راجع طلباتك.',
    completeTamaraTab: 'أكمل دفع تمارا في النافذة الجديدة ثم عد هنا.',
    tamaraFailed: 'فشل دفع تمارا. حاول مرة أخرى.',
    paymentCardTitle: 'بطاقة ائتمان / خصم',
    paymentTamaraTitle: 'تمارا — اشترِ الآن وادفع لاحقاً',
    itemsInOrder: 'المنتجات ({n})',
    loginHeroTitle1: 'أسعار تنخفض',
    loginHeroTitle2: 'أمام عينيك.',
    loginHeroBody: 'تسوق في سوق ديناميكي حيث ينخفض سعر كل منتج بشكل مباشر. زايد في مزادات حصرية. عيّن تنبيهات سعر. واربح.',
    loginStatProductsValue: 'ديناميكية',
    loginStatProducts: 'منتجات',
    loginStatLive: 'مباشر',
    registerHeroTitle1: 'شاهد الأسعار تنخفض',
    registerHeroTitle2: 'ووفّر عند التسوّق.',
    registerHeroBody: 'أنشئ حسابك لتتبع انخفاض الأسعار المباشرة وتعيين التنبيهات والمزايدة في مزادات حصرية — كل ذلك في مكان واحد.',
    registerIntro: 'أدخل اسمك ورقم جوالك للبدء.',
    otpEnterCode: 'أدخل الرمز',
    otpSentLine: 'أرسلنا رمزاً من {n} أرقام إلى',
    verifyCode: 'تحقق من الرمز',
    changeNumber: 'تغيير الرقم',
    resendIn: 'إعادة الإرسال خلال {s} ث',
    resendCode: 'إعادة إرسال الرمز',
    deleteAccountTitle: 'حذف الحساب؟',
    phoneExamplePlaceholder: '5X XXX XXXX',
    profileGuestTitle: 'سجّل الدخول لعرض ملفك',
    profileGuestDesc: 'الوصول إلى طلباتك والمفضلة والإعدادات.',
    dangerZone: 'منطقة الخطر',
    loginCopyright: '© {year} منصة حسم',
  },
};

function interpolate(str, vars) {
  if (!str || typeof str !== 'string') return str;
  return str.replace(/\{(\w+)\}/g, (_, k) => (vars[k] != null ? String(vars[k]) : `{${k}}`));
}

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('hasm_lang') || 'ar');

  useLayoutEffect(() => {
    try {
      localStorage.setItem('hasm_lang', lang);
    } catch (_) {}
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
    const title =
      translations[lang]?.documentTitle ??
      translations.ar.documentTitle ??
      translations.en.documentTitle;
    if (title) document.title = title;
    const metaDesc =
      lang === 'ar'
        ? 'حسم — سوق تسعير ديناميكي. تنخفض الأسعار بشكل مباشر.'
        : 'Hasm — dynamic pricing marketplace. Prices drop in real time.';
    let meta = document.querySelector('meta[name="description"]');
    if (!meta) {
      meta = document.createElement('meta');
      meta.setAttribute('name', 'description');
      document.head.appendChild(meta);
    }
    meta.setAttribute('content', metaDesc);
  }, [lang]);

  const resolve = (key) =>
    translations[lang]?.[key] ??
    translations.ar[key] ??
    translations.en[key] ??
    key;

  const t = (key) => resolve(key);

  const tf = (key, vars = {}) => interpolate(String(resolve(key)), vars);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, tf, isRTL: lang === 'ar' }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};
